[package]
name = "document_hasher_rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "document_hasher_rust"
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
hmac = "0.12.1"
pyo3 = "0.25.1"
sha2 = "0.10.9"
